///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test00
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ChangeData_01 recording.
    /// </summary>
    [TestModule("db741196-e6d7-4af7-ad1e-43816e404878", ModuleType.Recording, 1)]
    public partial class ChangeData_01 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Test00Repository repository.
        /// </summary>
        public static Test00Repository repo = Test00Repository.Instance;

        static ChangeData_01 instance = new ChangeData_01();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ChangeData_01()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ChangeData_01 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.IWillEnterPasteInMyData1' at 18;12.", repo.NewProtocolWizard.SomeContainer2.IWillEnterPasteInMyData1Info, new RecordItemIndex(0));
            repo.NewProtocolWizard.SomeContainer2.IWillEnterPasteInMyData1.Click("18;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.Next' at 29;7.", repo.NewProtocolWizard.SomeContainer2.NextInfo, new RecordItemIndex(1));
            repo.NewProtocolWizard.SomeContainer2.Next.Click("29;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.SomeList' at 91;89.", repo.NewProtocolWizard.SomeContainer2.SomeListInfo, new RecordItemIndex(2));
            repo.NewProtocolWizard.SomeContainer2.SomeList.Click("91;89");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.SomeList1' at 50;56.", repo.NewProtocolWizard.SomeContainer2.SomeList1Info, new RecordItemIndex(3));
            repo.NewProtocolWizard.SomeContainer2.SomeList1.Click("50;56");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.Next' at 27;6.", repo.NewProtocolWizard.SomeContainer2.NextInfo, new RecordItemIndex(4));
            repo.NewProtocolWizard.SomeContainer2.Next.Click("27;6");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
