///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test00
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ChangeData recording.
    /// </summary>
    [TestModule("410718be-be5c-4b26-ab83-18c93fb1c6b6", ModuleType.Recording, 1)]
    public partial class ChangeData : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Test00Repository repository.
        /// </summary>
        public static Test00Repository repo = Test00Repository.Instance;

        static ChangeData instance = new ChangeData();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ChangeData()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ChangeData Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.IWillEnterPasteInMyData' at 11;8.", repo.NewProtocolWizard.SomeContainer2.IWillEnterPasteInMyDataInfo, new RecordItemIndex(0));
            repo.NewProtocolWizard.SomeContainer2.IWillEnterPasteInMyData.Click("11;8");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.Next' at 28;9.", repo.NewProtocolWizard.SomeContainer2.NextInfo, new RecordItemIndex(1));
            repo.NewProtocolWizard.SomeContainer2.Next.Click("28;9");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.SomeList' at 125;42.", repo.NewProtocolWizard.SomeContainer2.SomeListInfo, new RecordItemIndex(2));
            repo.NewProtocolWizard.SomeContainer2.SomeList.Click("125;42");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.SomeList1' at 64;40.", repo.NewProtocolWizard.SomeContainer2.SomeList1Info, new RecordItemIndex(3));
            repo.NewProtocolWizard.SomeContainer2.SomeList1.Click("64;40");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.Next' at 24;8.", repo.NewProtocolWizard.SomeContainer2.NextInfo, new RecordItemIndex(4));
            repo.NewProtocolWizard.SomeContainer2.Next.Click("24;8");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
