///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test00
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckBoxOff recording.
    /// </summary>
    [TestModule("07aba781-2cbc-496b-bfba-afba8587d6fc", ModuleType.Recording, 1)]
    public partial class CheckBoxOff : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Test00Repository repository.
        /// </summary>
        public static Test00Repository repo = Test00Repository.Instance;

        static CheckBoxOff instance = new CheckBoxOff();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckBoxOff()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckBoxOff Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.SomeCheckBox' at 4;5.", repo.NewProtocolWizard.SomeContainer2.SomeCheckBoxInfo, new RecordItemIndex(0));
            repo.NewProtocolWizard.SomeContainer2.SomeCheckBox.Click("4;5");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='False') on item 'NewProtocolWizard.SomeContainer2.SomeCheckBox'.", repo.NewProtocolWizard.SomeContainer2.SomeCheckBoxInfo, new RecordItemIndex(1));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer2.SomeCheckBoxInfo, "Checked", "False");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.IndeterminateMark2' at 6;3.", repo.NewProtocolWizard.SomeContainer2.IndeterminateMark2Info, new RecordItemIndex(2));
            repo.NewProtocolWizard.SomeContainer2.IndeterminateMark2.Click("6;3");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.IndeterminateMark3' at 6;6.", repo.NewProtocolWizard.SomeContainer2.IndeterminateMark3Info, new RecordItemIndex(3));
            repo.NewProtocolWizard.SomeContainer2.IndeterminateMark3.Click("6;6");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.IndeterminateMark' at 6;1.", repo.NewProtocolWizard.SomeContainer2.IndeterminateMarkInfo, new RecordItemIndex(4));
            repo.NewProtocolWizard.SomeContainer2.IndeterminateMark.Click("6;1");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='False') on item 'NewProtocolWizard.SomeContainer2.SomeCheckBox1'.", repo.NewProtocolWizard.SomeContainer2.SomeCheckBox1Info, new RecordItemIndex(5));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer2.SomeCheckBox1Info, "Checked", "False");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.Next' at 17;7.", repo.NewProtocolWizard.SomeContainer2.NextInfo, new RecordItemIndex(6));
            repo.NewProtocolWizard.SomeContainer2.Next.Click("17;7");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'LayoutEditor1'.", repo.LayoutEditor1.SelfInfo, new RecordItemIndex(7));
            Validate.Exists(repo.LayoutEditor1.SelfInfo);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor1.ButtonOK' at 46;14.", repo.LayoutEditor1.ButtonOKInfo, new RecordItemIndex(8));
            repo.LayoutEditor1.ButtonOK.Click("46;14");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.IndeterminateMark4' at 5;0.", repo.NewProtocolWizard.SomeContainer2.IndeterminateMark4Info, new RecordItemIndex(9));
            repo.NewProtocolWizard.SomeContainer2.IndeterminateMark4.Click("5;0");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='True') on item 'NewProtocolWizard.SomeContainer2.SomeCheckBox'.", repo.NewProtocolWizard.SomeContainer2.SomeCheckBoxInfo, new RecordItemIndex(10));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer2.SomeCheckBoxInfo, "Checked", "True");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.IndeterminateMark' at 7;3.", repo.NewProtocolWizard.SomeContainer2.IndeterminateMarkInfo, new RecordItemIndex(11));
            repo.NewProtocolWizard.SomeContainer2.IndeterminateMark.Click("7;3");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='True') on item 'NewProtocolWizard.SomeContainer2.SomeCheckBox1'.", repo.NewProtocolWizard.SomeContainer2.SomeCheckBox1Info, new RecordItemIndex(12));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer2.SomeCheckBox1Info, "Checked", "True");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.Next' at 13;5.", repo.NewProtocolWizard.SomeContainer2.NextInfo, new RecordItemIndex(13));
            repo.NewProtocolWizard.SomeContainer2.Next.Click("13;5");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Select how your samples are arranged. Use an existing layout or create a new one.') on item 'NewProtocolWizard.SomeContainer2.SelectHowYourSamplesAreArrangedUs'.", repo.NewProtocolWizard.SomeContainer2.SelectHowYourSamplesAreArrangedUsInfo, new RecordItemIndex(14));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer2.SelectHowYourSamplesAreArrangedUsInfo, "Text", "Select how your samples are arranged. Use an existing layout or create a new one.");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.Close' at 22;13.", repo.NewProtocolWizard.CloseInfo, new RecordItemIndex(15));
            repo.NewProtocolWizard.Close.Click("22;13");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
