///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test00
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CreateNewMicroplate recording.
    /// </summary>
    [TestModule("1feb6012-4260-4009-9fee-26739c7755e1", ModuleType.Recording, 1)]
    public partial class CreateNewMicroplate : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Test00Repository repository.
        /// </summary>
        public static Test00Repository repo = Test00Repository.Instance;

        static CreateNewMicroplate instance = new CreateNewMicroplate();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CreateNewMicroplate()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CreateNewMicroplate Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer' at 44;2.", repo.NewProtocolWizard.SomeContainerInfo, new RecordItemIndex(0));
            repo.NewProtocolWizard.SomeContainer.Click("44;2");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysDesktopExplorer.ListView' at 61;29.", repo.MyAssaysDesktopExplorer.ListViewInfo, new RecordItemIndex(1));
            repo.MyAssaysDesktopExplorer.ListView.Click("61;29");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.SomeList.LargeImage1' at 8;17.", repo.LayoutEditor.SomeList.LargeImage1Info, new RecordItemIndex(2));
            repo.LayoutEditor.SomeList.LargeImage1.Click("8;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.PARTElementPlateGrid.MAINRECT' at 516;357.", repo.LayoutEditor.PARTElementPlateGrid.MAINRECTInfo, new RecordItemIndex(3));
            repo.LayoutEditor.PARTElementPlateGrid.MAINRECT.Click("516;357");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot2' with region {X=0,Y=0,Width=102,Height=102}) on item 'LayoutEditor.PARTElementPlateGrid.LAYOUT23'.", repo.LayoutEditor.PARTElementPlateGrid.LAYOUT23Info, new RecordItemIndex(4));
            Validate.CompareImage(repo.LayoutEditor.PARTElementPlateGrid.LAYOUT23Info, LAYOUT23_Screenshot2, LAYOUT23_Screenshot2_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.PARTElementPlateGrid.MAINRECT' at 432;352.", repo.LayoutEditor.PARTElementPlateGrid.MAINRECTInfo, new RecordItemIndex(5));
            repo.LayoutEditor.PARTElementPlateGrid.MAINRECT.Click("432;352");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.PARTElementPlateGrid.MAINRECT' at 333;340.", repo.LayoutEditor.PARTElementPlateGrid.MAINRECTInfo, new RecordItemIndex(6));
            repo.LayoutEditor.PARTElementPlateGrid.MAINRECT.Click("333;340");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.PARTElementPlateGrid.MAINRECT' at 241;335.", repo.LayoutEditor.PARTElementPlateGrid.MAINRECTInfo, new RecordItemIndex(7));
            repo.LayoutEditor.PARTElementPlateGrid.MAINRECT.Click("241;335");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.SomeList.LargeImage' at 4;9.", repo.LayoutEditor.SomeList.LargeImageInfo, new RecordItemIndex(8));
            repo.LayoutEditor.SomeList.LargeImage.Click("4;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.PARTElementPlateGrid.MAINRECT' at 255;365.", repo.LayoutEditor.PARTElementPlateGrid.MAINRECTInfo, new RecordItemIndex(9));
            repo.LayoutEditor.PARTElementPlateGrid.MAINRECT.Click("255;365");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'LayoutEditor.PARTElementPlateGrid.LAYOUT20'.", repo.LayoutEditor.PARTElementPlateGrid.LAYOUT20Info, new RecordItemIndex(10));
            Validate.Exists(repo.LayoutEditor.PARTElementPlateGrid.LAYOUT20Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.SomeContainer2.SomeElement1' at 13;10.", repo.LayoutEditor.SomeContainer2.SomeElement1Info, new RecordItemIndex(11));
            repo.LayoutEditor.SomeContainer2.SomeElement1.Click("13;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.PARTElementPlateGrid.MAINRECT' at 373;345.", repo.LayoutEditor.PARTElementPlateGrid.MAINRECTInfo, new RecordItemIndex(12));
            repo.LayoutEditor.PARTElementPlateGrid.MAINRECT.Click("373;345");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'LayoutEditor.PARTElementPlateGrid.LAYOUT21'.", repo.LayoutEditor.PARTElementPlateGrid.LAYOUT21Info, new RecordItemIndex(13));
            Validate.Exists(repo.LayoutEditor.PARTElementPlateGrid.LAYOUT21Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.SomeContainer2.Control' at 21;5.", repo.LayoutEditor.SomeContainer2.ControlInfo, new RecordItemIndex(14));
            repo.LayoutEditor.SomeContainer2.Control.Click("21;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.PARTElementPlateGrid.MAINRECT' at 458;345.", repo.LayoutEditor.PARTElementPlateGrid.MAINRECTInfo, new RecordItemIndex(15));
            repo.LayoutEditor.PARTElementPlateGrid.MAINRECT.Click("458;345");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'LayoutEditor.PARTElementPlateGrid.LAYOUT22'.", repo.LayoutEditor.PARTElementPlateGrid.LAYOUT22Info, new RecordItemIndex(16));
            Validate.Exists(repo.LayoutEditor.PARTElementPlateGrid.LAYOUT22Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.SomeContainer2.Unknown' at 24;6.", repo.LayoutEditor.SomeContainer2.UnknownInfo, new RecordItemIndex(17));
            repo.LayoutEditor.SomeContainer2.Unknown.Click("24;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.PARTElementPlateGrid.MAINRECT' at 545;326.", repo.LayoutEditor.PARTElementPlateGrid.MAINRECTInfo, new RecordItemIndex(18));
            repo.LayoutEditor.PARTElementPlateGrid.MAINRECT.Click("545;326");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'LayoutEditor.PARTElementPlateGrid.LAYOUT23'.", repo.LayoutEditor.PARTElementPlateGrid.LAYOUT23Info, new RecordItemIndex(19));
            Validate.Exists(repo.LayoutEditor.PARTElementPlateGrid.LAYOUT23Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='21') on item 'LayoutEditor.PARTElementPlateGrid.TEXT23'.", repo.LayoutEditor.PARTElementPlateGrid.TEXT23Info, new RecordItemIndex(20));
            Validate.Attribute(repo.LayoutEditor.PARTElementPlateGrid.TEXT23Info, "Text", "21");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.ElementPlateRibbonBar.PARTImage' at 9;30.", repo.LayoutEditor.ElementPlateRibbonBar.PARTImageInfo, new RecordItemIndex(21));
            repo.LayoutEditor.ElementPlateRibbonBar.PARTImage.Click("9;30");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot2' with region {X=0,Y=0,Width=646,Height=461}) on item 'LayoutEditor.PARTElementPlateGrid.RootCanvas'.", repo.LayoutEditor.PARTElementPlateGrid.RootCanvasInfo, new RecordItemIndex(22));
            Validate.CompareImage(repo.LayoutEditor.PARTElementPlateGrid.RootCanvasInfo, RootCanvas_Screenshot2, RootCanvas_Screenshot2_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.PARTElementPlateGrid.MAINRECT' at 61;50.", repo.LayoutEditor.PARTElementPlateGrid.MAINRECTInfo, new RecordItemIndex(23));
            repo.LayoutEditor.PARTElementPlateGrid.MAINRECT.Click("61;50");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'LayoutEditor.PARTElementPlateGrid.LAYOUT0'.", repo.LayoutEditor.PARTElementPlateGrid.LAYOUT0Info, new RecordItemIndex(24));
            Validate.Exists(repo.LayoutEditor.PARTElementPlateGrid.LAYOUT0Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='1') on item 'LayoutEditor.PARTElementPlateGrid.TEXT0'.", repo.LayoutEditor.PARTElementPlateGrid.TEXT0Info, new RecordItemIndex(25));
            Validate.Attribute(repo.LayoutEditor.PARTElementPlateGrid.TEXT0Info, "Text", "1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=41,Height=26}) on item 'LayoutEditor.SomeElement'.", repo.LayoutEditor.SomeElementInfo, new RecordItemIndex(26));
            Validate.CompareImage(repo.LayoutEditor.SomeElementInfo, SomeElement_Screenshot1, SomeElement_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.ElementPlateRibbonBar.Remove' at 30;6.", repo.LayoutEditor.ElementPlateRibbonBar.RemoveInfo, new RecordItemIndex(27));
            repo.LayoutEditor.ElementPlateRibbonBar.Remove.Click("30;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot3' with region {X=0,Y=0,Width=216,Height=512}) on item 'LayoutEditor.PARTElementPlateGrid.PARTElementPlateListView'.", repo.LayoutEditor.PARTElementPlateGrid.PARTElementPlateListViewInfo, new RecordItemIndex(28));
            Validate.CompareImage(repo.LayoutEditor.PARTElementPlateGrid.PARTElementPlateListViewInfo, PARTElementPlateListView_Screenshot3, PARTElementPlateListView_Screenshot3_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.ElementPlateRibbonBar.Duplicate' at 8;3.", repo.LayoutEditor.ElementPlateRibbonBar.DuplicateInfo, new RecordItemIndex(29));
            repo.LayoutEditor.ElementPlateRibbonBar.Duplicate.Click("8;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot2' with region {X=0,Y=0,Width=216,Height=512}) on item 'LayoutEditor.PARTElementPlateGrid.PARTElementPlateListView'.", repo.LayoutEditor.PARTElementPlateGrid.PARTElementPlateListViewInfo, new RecordItemIndex(30));
            Validate.CompareImage(repo.LayoutEditor.PARTElementPlateGrid.PARTElementPlateListViewInfo, PARTElementPlateListView_Screenshot2, PARTElementPlateListView_Screenshot2_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.SomeList.Clear' at 14;7.", repo.LayoutEditor.SomeList.ClearInfo, new RecordItemIndex(31));
            repo.LayoutEditor.SomeList.Clear.Click("14;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot2' with region {X=0,Y=0,Width=646,Height=461}) on item 'LayoutEditor.PARTElementPlateGrid.RootCanvas'.", repo.LayoutEditor.PARTElementPlateGrid.RootCanvasInfo, new RecordItemIndex(32));
            Validate.CompareImage(repo.LayoutEditor.PARTElementPlateGrid.RootCanvasInfo, RootCanvas_Screenshot2_2, RootCanvas_Screenshot2_2_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.ElementPlateRibbonBar.PARTImage1' at 29;26.", repo.LayoutEditor.ElementPlateRibbonBar.PARTImage1Info, new RecordItemIndex(33));
            repo.LayoutEditor.ElementPlateRibbonBar.PARTImage1.Click("29;26");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.SomeList.And' at 18;-3.", repo.LayoutEditor.SomeList.AndInfo, new RecordItemIndex(34));
            repo.LayoutEditor.SomeList.And.Click("18;-3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.Next' at 21;7.", repo.NewProtocolWizard.SomeContainer2.NextInfo, new RecordItemIndex(35));
            repo.NewProtocolWizard.SomeContainer2.Next.Click("21;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.Закрити' at 25;10.", repo.NewProtocolWizard.ЗакритиInfo, new RecordItemIndex(36));
            repo.NewProtocolWizard.Закрити.Click("25;10");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
        CompressedImage LAYOUT23_Screenshot2
        { get { return repo.LayoutEditor.PARTElementPlateGrid.LAYOUT23Info.GetScreenshot2(new Rectangle(0, 0, 102, 102)); } }

        Imaging.FindOptions LAYOUT23_Screenshot2_Options
        { get { return Imaging.FindOptions.Parse("1;None;0,0,102,102;True;10000000;0ms"); } }

        CompressedImage RootCanvas_Screenshot2
        { get { return repo.LayoutEditor.PARTElementPlateGrid.RootCanvasInfo.GetScreenshot2(new Rectangle(0, 0, 646, 461)); } }

        Imaging.FindOptions RootCanvas_Screenshot2_Options
        { get { return Imaging.FindOptions.Parse("1;None;0,0,646,461;True;10000000;0ms"); } }

        CompressedImage SomeElement_Screenshot1
        { get { return repo.LayoutEditor.SomeElementInfo.GetScreenshot1(new Rectangle(0, 0, 41, 26)); } }

        Imaging.FindOptions SomeElement_Screenshot1_Options
        { get { return Imaging.FindOptions.Parse("1;None;0,0,41,26;True;10000000;0ms"); } }

        CompressedImage PARTElementPlateListView_Screenshot3
        { get { return repo.LayoutEditor.PARTElementPlateGrid.PARTElementPlateListViewInfo.GetScreenshot3(new Rectangle(0, 0, 216, 512)); } }

        Imaging.FindOptions PARTElementPlateListView_Screenshot3_Options
        { get { return Imaging.FindOptions.Parse("1;None;0,0,216,512;True;10000000;0ms"); } }

        CompressedImage PARTElementPlateListView_Screenshot2
        { get { return repo.LayoutEditor.PARTElementPlateGrid.PARTElementPlateListViewInfo.GetScreenshot2(new Rectangle(0, 0, 216, 512)); } }

        Imaging.FindOptions PARTElementPlateListView_Screenshot2_Options
        { get { return Imaging.FindOptions.Parse("1;None;0,0,216,512;True;10000000;0ms"); } }

        CompressedImage RootCanvas_Screenshot2_2
        { get { return repo.LayoutEditor.PARTElementPlateGrid.RootCanvasInfo.GetScreenshot2(new Rectangle(0, 0, 646, 461)); } }

        Imaging.FindOptions RootCanvas_Screenshot2_2_Options
        { get { return Imaging.FindOptions.Parse("1;None;0,0,646,461;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
