///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test00
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CreateSamples recording.
    /// </summary>
    [TestModule("3c535f63-261f-45e3-ad28-b77d7d091b9b", ModuleType.Recording, 1)]
    public partial class CreateSamples : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Test00Repository repository.
        /// </summary>
        public static Test00Repository repo = Test00Repository.Instance;

        static CreateSamples instance = new CreateSamples();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CreateSamples()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CreateSamples Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.CreateMultipleLayoutButton' at 68;18.", repo.NewProtocolWizard.CreateMultipleLayoutButtonInfo, new RecordItemIndex(0));
            repo.NewProtocolWizard.CreateMultipleLayoutButton.Click("68;18");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RackLayoutEditor.SomeContainer1.PARTElementAddSampleButton' at 45;9.", repo.RackLayoutEditor.SomeContainer1.PARTElementAddSampleButtonInfo, new RecordItemIndex(1));
            repo.RackLayoutEditor.SomeContainer1.PARTElementAddSampleButton.Click("45;9");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RackLayoutEditor.PARTElementRibbon.And' at 16;-3.", repo.RackLayoutEditor.PARTElementRibbon.AndInfo, new RecordItemIndex(2));
            repo.RackLayoutEditor.PARTElementRibbon.And.Click("16;-3");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.Next' at 33;5.", repo.NewProtocolWizard.SomeContainer2.NextInfo, new RecordItemIndex(3));
            repo.NewProtocolWizard.SomeContainer2.Next.Click("33;5");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
