///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test00
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CreateNewSamples recording.
    /// </summary>
    [TestModule("e1ab1dfe-ef0e-4fdd-8ab1-084694c29c16", ModuleType.Recording, 1)]
    public partial class CreateNewSamples : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Test00Repository repository.
        /// </summary>
        public static Test00Repository repo = Test00Repository.Instance;

        static CreateNewSamples instance = new CreateNewSamples();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CreateNewSamples()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CreateNewSamples Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.CreateMultipleLayoutButton' at 41;17.", repo.NewProtocolWizard.CreateMultipleLayoutButtonInfo, new RecordItemIndex(0));
            repo.NewProtocolWizard.CreateMultipleLayoutButton.Click("41;17");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RackLayoutEditor.PARTElementAddButtonTextBlock' at 26;9.", repo.RackLayoutEditor.PARTElementAddButtonTextBlockInfo, new RecordItemIndex(1));
            repo.RackLayoutEditor.PARTElementAddButtonTextBlock.Click("26;9");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RackLayoutEditor.PARTElementRibbon.PARTImage1' at 20;32.", repo.RackLayoutEditor.PARTElementRibbon.PARTImage1Info, new RecordItemIndex(2));
            repo.RackLayoutEditor.PARTElementRibbon.PARTImage1.Click("20;32");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RackLayoutEditor.PARTElementRibbon.PARTImage2' at 5;22.", repo.RackLayoutEditor.PARTElementRibbon.PARTImage2Info, new RecordItemIndex(3));
            repo.RackLayoutEditor.PARTElementRibbon.PARTImage2.Click("5;22");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RackLayoutEditor.PARTElementRibbon.PARTImage2' at 29;28.", repo.RackLayoutEditor.PARTElementRibbon.PARTImage2Info, new RecordItemIndex(4));
            repo.RackLayoutEditor.PARTElementRibbon.PARTImage2.Click("29;28");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RackLayoutEditor.PARTElementRibbon.InnerPath3' at 29;36.", repo.RackLayoutEditor.PARTElementRibbon.InnerPath3Info, new RecordItemIndex(5));
            repo.RackLayoutEditor.PARTElementRibbon.InnerPath3.Click("29;36");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RackLayoutEditor.PARTElementRibbon.SomeContainer1' at 5;32.", repo.RackLayoutEditor.PARTElementRibbon.SomeContainer1Info, new RecordItemIndex(6));
            repo.RackLayoutEditor.PARTElementRibbon.SomeContainer1.Click("5;32");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RackLayoutEditor.PARTElementRibbon.InnerPath1' at 48;36.", repo.RackLayoutEditor.PARTElementRibbon.InnerPath1Info, new RecordItemIndex(7));
            repo.RackLayoutEditor.PARTElementRibbon.InnerPath1.Click("48;36");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
