///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test00
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CreateNewProtocol recording.
    /// </summary>
    [TestModule("d66f0348-4405-484e-a704-ae8c33394447", ModuleType.Recording, 1)]
    public partial class CreateNewProtocol : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Test00Repository repository.
        /// </summary>
        public static Test00Repository repo = Test00Repository.Instance;

        static CreateNewProtocol instance = new CreateNewProtocol();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CreateNewProtocol()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CreateNewProtocol Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysExplorer.Protocols' at 56;6.", repo.MyAssaysExplorer.ProtocolsInfo, new RecordItemIndex(0));
            repo.MyAssaysExplorer.Protocols.Click("56;6");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysExplorer.PARTImage' at 17;30.", repo.MyAssaysExplorer.PARTImageInfo, new RecordItemIndex(1));
            repo.MyAssaysExplorer.PARTImage.Click("17;30");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
