///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test00
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DataFormat recording.
    /// </summary>
    [TestModule("a43ef4ca-24fd-4970-bee6-f7704d901417", ModuleType.Recording, 1)]
    public partial class DataFormat : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Test00Repository repository.
        /// </summary>
        public static Test00Repository repo = Test00Repository.Instance;

        static DataFormat instance = new DataFormat();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DataFormat()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DataFormat Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'NewProtocolWizard.SomeContainer2.SomeElement' at 18;10.", repo.NewProtocolWizard.SomeContainer2.SomeElementInfo, new RecordItemIndex(0));
            repo.NewProtocolWizard.SomeContainer2.SomeElement.MoveTo("18;10");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'NewProtocolWizard.SomeContainer2.SomeElement' at 26;2.", repo.NewProtocolWizard.SomeContainer2.SomeElementInfo, new RecordItemIndex(1));
            repo.NewProtocolWizard.SomeContainer2.SomeElement.MoveTo("26;2");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'NewProtocolWizard.SomeContainer2.SomeContainer' at 174;9.", repo.NewProtocolWizard.SomeContainer2.SomeContainerInfo, new RecordItemIndex(2));
            repo.NewProtocolWizard.SomeContainer2.SomeContainer.MoveTo("174;9");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '15'.", new RecordItemIndex(3));
            Keyboard.Press("15");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.Next' at 27;3.", repo.NewProtocolWizard.SomeContainer2.NextInfo, new RecordItemIndex(4));
            repo.NewProtocolWizard.SomeContainer2.Next.Click("27;3");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.Next' at 34;9.", repo.NewProtocolWizard.SomeContainer2.NextInfo, new RecordItemIndex(5));
            repo.NewProtocolWizard.SomeContainer2.Next.Click("34;9");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
