///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test00
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SomeTextTestAndFinish recording.
    /// </summary>
    [TestModule("42b370c8-9d6e-43c4-9535-43710dea9979", ModuleType.Recording, 1)]
    public partial class SomeTextTestAndFinish : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Test00Repository repository.
        /// </summary>
        public static Test00Repository repo = Test00Repository.Instance;

        static SomeTextTestAndFinish instance = new SomeTextTestAndFinish();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SomeTextTestAndFinish()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SomeTextTestAndFinish Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.MultipleContainerViewPanel.DataFormatToggleButton' at 46;5.", repo.NewProtocolWizard.MultipleContainerViewPanel.DataFormatToggleButtonInfo, new RecordItemIndex(0));
            repo.NewProtocolWizard.MultipleContainerViewPanel.DataFormatToggleButton.Click("46;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.MultipleContainerViewPanel.SomeElement' at 203;98.", repo.NewProtocolWizard.MultipleContainerViewPanel.SomeElementInfo, new RecordItemIndex(1));
            repo.NewProtocolWizard.MultipleContainerViewPanel.SomeElement.Click("203;98");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}'.", new RecordItemIndex(2));
            Keyboard.Press("{LControlKey down}{Akey}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Ckey}'.", new RecordItemIndex(3));
            Keyboard.Press("{Ckey}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Xkey}{LControlKey up}'.", new RecordItemIndex(4));
            Keyboard.Press("{Xkey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Measurements data could not be resolved.') on item 'NewProtocolWizard.SomeContainer2.MeasurementsDataCouldNotBeResolved'.", repo.NewProtocolWizard.SomeContainer2.MeasurementsDataCouldNotBeResolvedInfo, new RecordItemIndex(5));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer2.MeasurementsDataCouldNotBeResolvedInfo, "Text", "Measurements data could not be resolved.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'www'.", new RecordItemIndex(6));
            Keyboard.Press("www");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.MultipleContainerViewPanel.ClearButton' at 7;18.", repo.NewProtocolWizard.MultipleContainerViewPanel.ClearButtonInfo, new RecordItemIndex(7));
            repo.NewProtocolWizard.MultipleContainerViewPanel.ClearButton.Click("7;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.MultipleContainerViewPanel.PasteButton' at 60;7.", repo.NewProtocolWizard.MultipleContainerViewPanel.PasteButtonInfo, new RecordItemIndex(8));
            repo.NewProtocolWizard.MultipleContainerViewPanel.PasteButton.Click("60;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.MultipleContainerViewPanel.Racks' at 23;6.", repo.NewProtocolWizard.MultipleContainerViewPanel.RacksInfo, new RecordItemIndex(9));
            repo.NewProtocolWizard.MultipleContainerViewPanel.Racks.Click("23;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.MultipleContainerViewPanel.SomeElement1' at 33;8.", repo.NewProtocolWizard.MultipleContainerViewPanel.SomeElement1Info, new RecordItemIndex(10));
            repo.NewProtocolWizard.MultipleContainerViewPanel.SomeElement1.Click("33;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '2222222{Return}'.", new RecordItemIndex(11));
            Keyboard.Press("2222222{Return}");
            Delay.Milliseconds(0);
            
            // ????
            Report.Log(ReportLevel.Info, "Validation", "????\r\nValidating Exists on item 'NewProtocolWizard.MultipleContainerViewPanel.SomeElement1'.", repo.NewProtocolWizard.MultipleContainerViewPanel.SomeElement1Info, new RecordItemIndex(12));
            Validate.Exists(repo.NewProtocolWizard.MultipleContainerViewPanel.SomeElement1Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.MultipleContainerViewPanel.TextPad' at 14;-1.", repo.NewProtocolWizard.MultipleContainerViewPanel.TextPadInfo, new RecordItemIndex(13));
            repo.NewProtocolWizard.MultipleContainerViewPanel.TextPad.Click("14;-1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.Next' at 42;15.", repo.NewProtocolWizard.SomeContainer2.NextInfo, new RecordItemIndex(14));
            repo.NewProtocolWizard.SomeContainer2.Next.Click("42;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.SomeElement1' at 396;89.", repo.NewProtocolWizard.SomeContainer2.SomeElement1Info, new RecordItemIndex(15));
            repo.NewProtocolWizard.SomeContainer2.SomeElement1.Click("396;89");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}S{LShiftKey up}ome{LShiftKey down}T{LShiftKey up}ext{Space}2{Space}{LShiftKey down}#{LShiftKey up}{Space down}{LShiftKey down}{Space up}@#!{LShiftKey up}450'.", new RecordItemIndex(16));
            Keyboard.Press("{LShiftKey down}S{LShiftKey up}ome{LShiftKey down}T{LShiftKey up}ext{Space}2{Space}{LShiftKey down}#{LShiftKey up}{Space down}{LShiftKey down}{Space up}@#!{LShiftKey up}450");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='SomeText 2 # @#!450') on item 'NewProtocolWizard.SomeContainer2.SomeText2HashAtHash450'.", repo.NewProtocolWizard.SomeContainer2.SomeText2HashAtHash450Info, new RecordItemIndex(17));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer2.SomeText2HashAtHash450Info, "Text", "SomeText 2 # @#!450");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.Next' at 23;5.", repo.NewProtocolWizard.SomeContainer2.NextInfo, new RecordItemIndex(18));
            repo.NewProtocolWizard.SomeContainer2.Next.Click("23;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.OptionMark3' at 9;5.", repo.NewProtocolWizard.SomeContainer2.OptionMark3Info, new RecordItemIndex(19));
            repo.NewProtocolWizard.SomeContainer2.OptionMark3.Click("9;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer2.Finish' at 37;13.", repo.NewProtocolWizard.SomeContainer2.FinishInfo, new RecordItemIndex(20));
            repo.NewProtocolWizard.SomeContainer2.Finish.Click("37;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysExplorer.MyEndpointDualRacksOf15Protocol1' at 182;4.", repo.MyAssaysExplorer.MyEndpointDualRacksOf15Protocol1Info, new RecordItemIndex(21));
            repo.MyAssaysExplorer.MyEndpointDualRacksOf15Protocol1.Click("182;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}'.", new RecordItemIndex(22));
            Keyboard.Press("{Delete}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating NotExists on item 'MyAssaysExplorer.MyEndpointDualRacksOf15Protocol1'.", repo.MyAssaysExplorer.MyEndpointDualRacksOf15Protocol1Info, new RecordItemIndex(23));
            Validate.NotExists(repo.MyAssaysExplorer.MyEndpointDualRacksOf15Protocol1Info);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
